#!/usr/bin/env python
"""
Argo GDAC NetCDF Downloader for Arabian Sea Floats

Uses the global index file (ar_index_global_prof.txt) to discover
correct DAC assignments and available cycles for each float.
"""
import argparse
import asyncio
import sys
import re
from pathlib import Path
from typing import List, Dict, Optional, Tuple, Set
import httpx
from tqdm import tqdm
from datetime import datetime

# Global index URL
GLOBAL_INDEX_URL = "https://data-argo.ifremer.fr/ar_index_global_prof.txt"
BASE_URL = "https://data-argo.ifremer.fr/dac"

# Top 30 Arabian Sea floats (discovered from global index, ranked by delayed-mode profile count)
# Source: arabian_sea_top30_floats.txt generated by discover_arabian_sea_floats.py
# Format: (WMO, DAC, Name)
TARGET_FLOATS = [
    ("6903059", "coriolis", "Central Arabian Sea (coriolis #1)"),
    ("6903060", "coriolis", "Central Arabian Sea (coriolis #2)"),
    ("6903063", "coriolis", "Western Arabian Sea (coriolis #3)"),
    ("6903058", "coriolis", "Western Arabian Sea (coriolis #4)"),
    ("2900090", "aoml", "Northern Arabian Sea (aoml #1)"),
    ("2901509", "csio", "Eastern Arabian Sea (csio #1)"),
    ("6902943", "coriolis", "Eastern Arabian Sea (coriolis #5)"),
    ("6903062", "coriolis", "Central Arabian Sea (coriolis #6)"),
    ("2900089", "aoml", "Northern Arabian Sea (aoml #2)"),
    ("2901447", "aoml", "Northern Arabian Sea (aoml #3)"),
    ("2901108", "aoml", "Central Arabian Sea (aoml #4)"),
    ("2901107", "aoml", "Central Arabian Sea (aoml #5)"),
    ("6903008", "coriolis", "Northern Arabian Sea (coriolis #7)"),
    ("2900394", "aoml", "Central Arabian Sea (aoml #6)"),
    ("6903046", "coriolis", "Northern Arabian Sea (coriolis #8)"),
    ("2901337", "incois", "Central Arabian Sea (incois #1)"),
    ("2901370", "aoml", "Northern Arabian Sea (aoml #7)"),
    ("2901372", "aoml", "Central Arabian Sea (aoml #8)"),
    ("2902390", "aoml", "Central Arabian Sea (aoml #9)"),
    ("6903007", "coriolis", "Western Arabian Sea (coriolis #9)"),
    ("2902203", "incois", "Central Arabian Sea (incois #2)"),
    ("2901444", "aoml", "Central Arabian Sea (aoml #10)"),
    ("2901339", "incois", "Central Arabian Sea (incois #3)"),
    ("2901338", "incois", "Central Arabian Sea (incois #4)"),
    ("2901466", "aoml", "Central Arabian Sea (aoml #11)"),
    ("2901415", "aoml", "Northern Arabian Sea (aoml #12)"),
    ("2901465", "aoml", "Northern Arabian Sea (aoml #13)"),
    ("2902391", "aoml", "Central Arabian Sea (aoml #14)"),
    ("2902206", "incois", "Central Arabian Sea (incois #5)"),
    ("2901132", "aoml", "Central Arabian Sea (aoml #15)"),
    # Tier 2 (global-index ranks 31-46, verified DACs) — added 2026-09-24
    ("2902389", "aoml", "Southern Arabian Sea (aoml #16)"),
    ("2901340", "incois", "Central Arabian Sea (incois #6)"),
    ("2902062", "aoml", "Central Arabian Sea (aoml #17)"),
    ("2901129", "aoml", "Central Arabian Sea (aoml #18)"),
    ("2901460", "aoml", "Central Arabian Sea (aoml #19)"),
    ("2901133", "aoml", "Eastern Arabian Sea (aoml #20)"),
    ("2901860", "csiro", "Western Arabian Sea (csiro #1)"),
    ("2900554", "incois", "Northern Arabian Sea (incois #7)"),
    ("2901431", "aoml", "Northern Arabian Sea (aoml #21)"),
    ("2901307", "incois", "Eastern Arabian Sea (incois #8)"),
    ("6902948", "coriolis", "Western Arabian Sea (coriolis #10)"),
    ("2901858", "csiro", "Central Arabian Sea (csiro #2)"),
    ("2902065", "aoml", "Northern Arabian Sea (aoml #22)"),
    ("2900556", "incois", "Central Arabian Sea (incois #9)"),
    ("2901457", "aoml", "Central Arabian Sea (aoml #23)"),
    ("2901856", "csiro", "Central Arabian Sea (csiro #3)"),
]

# Seed floats (for testing) - kept separate
SEED_FLOATS = [
    ("3902114", "coriolis", "Northern Arabian Sea / Gulf of Oman [SEED]"),
    ("2903334", "jma", "Central Arabian Sea Basin [SEED]"),
    ("1902442", "aoml", "Eastern Arabian Sea / Indian West Shelf [SEED]"),
    ("2902789", "csio", "Southwestern Upwelling Corridor [SEED]"),
]

# Combine all floats
ALL_FLOATS = TARGET_FLOATS + SEED_FLOATS

# Target WMO set for fast lookup (from TARGET_FLOATS + SEED_FLOATS)
TARGET_WMOS = set(wmo for wmo, _, _ in TARGET_FLOATS + SEED_FLOATS)

# Cache for global index
_global_index_cache: Optional[Dict[str, Dict]] = None


def parse_global_index(content: str) -> Dict[str, Dict]:
    """
    Parse ar_index_global_prof.txt to extract DAC and cycles for each WMO.
    
    Format: dac/wmo/profiles/D{wmo}_{CYCLE}.nc,date,lat,lon,...
    """
    result = {}
    
    # Pattern: dac/WMO/profiles/D{WMO}_{CYCLE}.nc (or DWMO_CYCLED.nc for delayed)
    pattern = r'^([^/]+)/(\d+)/profiles/D(\d+)_(\d{3})D?\.nc'
    
    for line in content.strip().split('\n'):
        if not line or line.startswith('#'):
            continue
        
        match = re.match(pattern, line)
        if match:
            dac, wmo, wmo2, cycle = match.groups()
            if wmo == wmo2 and wmo in TARGET_WMOS:
                if wmo not in result:
                    result[wmo] = {"dac": dac, "cycles": []}
                # Store as (cycle, date_str) tuple to allow year filtering
                # Extract date from line: format is ...,YYYYMMDD,... or ...,YYYYMMDDHHMMSS,...
                date_match = re.search(r',(\d{8,14}),', line)
                date_str = date_match.group(1) if date_match else ""
                result[wmo]["cycles"].append((int(cycle), date_str))
    
    # Sort cycles by cycle number
    for wmo in result:
        result[wmo]["cycles"].sort(key=lambda x: x[0])
    
    return result


def parse_year_args(year_arg: Optional[str], start_year: Optional[int], end_year: Optional[int]) -> Tuple[Optional[int], Optional[int]]:
    """
    Parse year arguments and return (start_year, end_year) tuple.
    
    Args:
        year_arg: String like "2023" or "2020-2023"
        start_year: Explicit start year
        end_year: Explicit end year
    
    Returns:
        Tuple of (start_year, end_year) where None means no limit
    """
    start = None
    end = None
    
    if year_arg:
        if "-" in year_arg:
            parts = year_arg.split("-")
            start = int(parts[0])
            end = int(parts[1])
        else:
            start = int(year_arg)
            end = int(year_arg)
    else:
        if start_year is not None:
            start = start_year
        if end_year is not None:
            end = end_year
    
    if start is not None and end is not None and start > end:
        raise ValueError("Start year cannot be greater than end year")
    
    return start, end


def filter_cycles_by_year(cycles: List[Tuple[int, str]], start_year: Optional[int], end_year: Optional[int]) -> List[int]:
    """
    Filter cycles by year range.
    
    Args:
        cycles: List of (cycle, date_str) tuples
        start_year: Inclusive start year
        end_year: Inclusive end year
    
    Returns:
        List of cycle numbers within the year range
    """
    if start_year is None and end_year is None:
        return [c for c, _ in cycles]
    
    filtered = []
    for cycle, date_str in cycles:
        if not date_str or len(date_str) < 4:
            # No date info, include by default
            if start_year is None and end_year is None:
                filtered.append(cycle)
            continue
        
        try:
            year = int(date_str[:4])
            if start_year is not None and year < start_year:
                continue
            if end_year is not None and year > end_year:
                continue
            filtered.append(cycle)
        except (ValueError, IndexError):
# If we can't parse the date, include it if no year filter
            if start_year is None and end_year is None:
                filtered.append(cycle)
    
    return filtered


async def fetch_global_index(client: httpx.AsyncClient, start_year: Optional[int] = None, end_year: Optional[int] = None) -> Dict[str, Dict]:
    """Fetch and parse the global index file."""
    global _global_index_cache
    
    if _global_index_cache is not None:
        return _global_index_cache
    
    print("Fetching global index (ar_index_global_prof.txt)...")
    resp = await client.get(GLOBAL_INDEX_URL, timeout=60.0)
    resp.raise_for_status()
    
    _global_index_cache = parse_global_index(resp.text)
    print(f"Parsed index: found {len(_global_index_cache)} target floats")
    
    # Filter by year if specified
    if start_year is not None or end_year is not None:
        for wmo in _global_index_cache:
            _global_index_cache[wmo]["cycles"] = filter_cycles_by_year(
                _global_index_cache[wmo]["cycles"], start_year, end_year
            )
        # Remove floats with no cycles after filtering
        _global_index_cache = {wmo: data for wmo, data in _global_index_cache.items() if data["cycles"]}
        print(f"After year filtering: {len(_global_index_cache)} target floats remain")
    
    return _global_index_cache


class ArgoDownloader:
    def __init__(self, output_dir: Path, max_concurrent: int = 3):
        self.output_dir = output_dir
        self.max_concurrent = max_concurrent
        self.semaphore = asyncio.Semaphore(max_concurrent)
        
    def get_profile_url(self, dac: str, wmo: str, cycle: int) -> str:
        """Construct NetCDF URL for a profile (D-prefix = delayed mode)."""
        cycle_str = f"{cycle:03d}"
        return f"{BASE_URL}/{dac}/{wmo}/profiles/D{wmo}_{cycle_str}.nc"
    
    async def download_profile(self, client: httpx.AsyncClient, dac: str, wmo: str, cycle: int, 
                               progress_bar: Optional[tqdm] = None) -> bool:
        """Download a single NetCDF profile."""
        url = self.get_profile_url(dac, wmo, cycle)
        output_path = self.output_dir / wmo / f"D{wmo}_{cycle:03d}.nc"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        if output_path.exists():
            if progress_bar:
                progress_bar.update(1)
            return True
        
        async with self.semaphore:
            try:
                async with client.stream("GET", url, timeout=60.0, follow_redirects=True) as resp:
                    if resp.status_code == 404:
                        return False
                    resp.raise_for_status()
                    
                    with open(output_path, "wb") as f:
                        async for chunk in resp.aiter_bytes(chunk_size=8192):
                            f.write(chunk)
                
                if progress_bar:
                    progress_bar.update(1)
                return True
                
            except Exception as e:
                if output_path.exists():
                    output_path.unlink()
                print(f"  Error downloading {wmo} cycle {cycle}: {e}")
                if progress_bar:
                    progress_bar.update(1)
                return False
    
    async def download_float(self, client: httpx.AsyncClient, wmo: str, dac: str, 
                             cycles: List[int], name: str) -> Dict:
        """Download all profiles for a single float."""
        print(f"\n{'='*60}")
        print(f"Downloading: {wmo} ({name})")
        print(f"DAC: {dac}")
        print(f"{'='*60}")
        
        if not cycles:
            print(f"  No cycles found for {wmo}")
            return {"wmo": wmo, "downloaded": 0, "total": 0, "cycles": []}
        
        print(f"  Found {len(cycles)} cycles: {cycles[0]} - {cycles[-1]}")
        
        downloaded = 0
        with tqdm(total=len(cycles), desc=f"  {wmo}", unit="file") as pbar:
            tasks = [
                self.download_profile(client, dac, wmo, cycle, pbar)
                for cycle in cycles
            ]
            results = await asyncio.gather(*tasks)
            downloaded = sum(results)
        
        return {"wmo": wmo, "downloaded": downloaded, "total": len(cycles), "cycles": cycles}


def load_floats_file(path: Path) -> List[tuple]:
    """Load a float list file: `WMO,DAC[,NAME]` or discovery output
    `WMO,DAC,N_CYCLES,AVG_LAT,AVG_LON,INSTITUTION` (`#` comments skipped)."""
    entries: List[tuple] = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split(",")]
        if len(parts) < 2:
            continue
        wmo, dac = parts[0], parts[1]
        if len(parts) >= 6:
            name = f"Float {wmo} ({parts[5]})"
        elif len(parts) >= 3 and parts[2]:
            name = parts[2]
        else:
            name = f"Float {wmo}"
        entries.append((wmo, dac, name))
    return entries


def build_float_list(index_data: Dict[str, Dict], source: List[tuple] | None = None) -> List[Dict]:
    """Build the list of floats from a target list, enriched with index data."""
    floats = []
    for wmo, dac, name in (source if source is not None else ALL_FLOATS):
        info = index_data.get(wmo)
        if info:
            floats.append({
                "wmo": wmo,
                "dac": dac,  # Use our verified DAC
                "name": name,
                "cycles": info["cycles"],
                "in_index": True
            })
        else:
            # Float not in index - might not exist or no delayed-mode profiles
            floats.append({
                "wmo": wmo,
                "dac": dac,
                "name": name + " [NOT IN INDEX]",
                "cycles": [],
                "in_index": False
            })
    return floats


def interactive_select(float_list: List[Dict]) -> List[Dict]:
    """Interactive float selection menu."""
    print("\n" + "="*70)
    print("ARABIAN SEA ARGO FLOATS - Interactive Selection")
    print("="*70)
    
    # Count floats with data vs not in index
    floats_in_index = [f for f in float_list if f["in_index"]]
    floats_not_in_index = [f for f in float_list if not f["in_index"]]
    
    print(f"Floats with data: {len(floats_in_index)}")
    print(f"Floats without data: {len(floats_not_in_index)}")
    print()
    
    display_floats = float_list
    
    for i, f in enumerate(float_list, 1):
        if f["in_index"]:
            cycles = f["cycles"]
            print(f"  [{i:2d}] {f['wmo']} (DAC: {f['dac']}, {len(cycles)} cycles: {cycles[0]}-{cycles[-1]}) - {f['name']}")
        else:
            print(f"  [{i:2d}] {f['wmo']} (DAC: {f['dac']}) - {f['name']} [NOT IN INDEX]")
    
    total = len(float_list)
    print("\nOptions:")
    print(f"  - Enter numbers separated by commas (e.g., 1,3,5)")
    print(f"  - Enter 'all' for all {total} floats")
    print(f"  - Enter 'range' for a range (e.g., 1-5)")
    print(f"  - Enter 'q' to quit")
    
    while True:
        choice = input("\nSelect floats: ").strip().lower()
        
        if choice == 'q':
            sys.exit(0)
        elif choice == 'all':
            return display_floats
        elif choice == 'target':
            return target_floats
        elif choice == 'seed':
            return seed_floats
        elif choice == 'range':
            try:
                r = input("  Enter range (e.g., 1-5): ").strip()
                start, end = map(int, r.split('-'))
                return display_floats[start-1:end]
            except:
                print("  Invalid range format")
                continue
        else:
            try:
                indices = [int(x.strip()) - 1 for x in choice.split(',')]
                selected = [display_floats[i] for i in indices if 0 <= i < len(display_floats)]
                if selected:
                    return selected
                print("  No valid selections")
            except:
                print("  Invalid input format")


async def run_download(output_dir: Path, selected_floats: List[Dict]):
    """Main download orchestrator."""
    print(f"\nOutput directory: {output_dir}")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    timeout = httpx.Timeout(60.0, connect=10.0)
    limits = httpx.Limits(max_keepalive_connections=5, max_connections=10)
    
    async with httpx.AsyncClient(timeout=timeout, limits=limits) as client:
        downloader = ArgoDownloader(output_dir)
        
        for f in selected_floats:
            if not f["in_index"]:
                print(f"\nSkipping {f['wmo']}: not found in global index")
                continue
            await downloader.download_float(client, f["wmo"], f["dac"], f["cycles"], f["name"])
    
    print(f"\n{'='*60}")
    print("DOWNLOAD COMPLETE")
    print(f"Files saved to: {output_dir}")
    print(f"{'='*60}")


def main():
    parser = argparse.ArgumentParser(description="Download Argo NetCDF profiles for Arabian Sea floats using global index")
    parser.add_argument("--output", "-o", type=Path, default=Path("../data/raw"),
                        help="Output directory (default: ../data/raw)")
    parser.add_argument("--float", "-f", type=str, help="WMO ID(s), comma-separated, to download")
    parser.add_argument("--floats-file", type=Path, default=None,
                        help="Float list file (discovery output or WMO,DAC[,NAME] rows); replaces the built-in list")
    parser.add_argument("--all", "-a", action="store_true", help="Download all floats from the index")
    
    parser.add_argument("--list", "-l", action="store_true", help="List available floats from index and exit")
    parser.add_argument("--concurrent", type=int, default=3, help="Max concurrent downloads")
    parser.add_argument("--year", type=str, help="Year(s) to download (e.g. '2023' or '2020-2023')")
    parser.add_argument("--start-year", type=int, help="Start year (inclusive)")
    parser.add_argument("--end-year", type=int, help="End year (inclusive)")
    parser.add_argument("--skip-existing", action="store_true", default=True, help="Skip already downloaded files (default: True)")
    
    args = parser.parse_args()
    
    # Float source: explicit file wins over the built-in list
    source = load_floats_file(args.floats_file) if args.floats_file else None
    if args.floats_file and not source:
        print(f"Error: no floats parsed from {args.floats_file}")
        sys.exit(1)

    # Fetch global index
    async def fetch_and_run():
        async with httpx.AsyncClient(timeout=60.0) as client:
            start_year, end_year = parse_year_args(args.year, args.start_year, args.end_year)
            index_data = await fetch_global_index(client, start_year, end_year)

            # Build float list with our target DACs
            float_list = build_float_list(index_data, source=source)
            
            if args.list:
                print(f"\nAvailable Floats ({len(float_list)} total):")
                print("="*70)
                for f in float_list:
                    status = "OK" if f["in_index"] else "MISSING"
                    cycles_info = f"{len(f['cycles'])} cycles ({min(f['cycles'])}-{max(f['cycles'])})" if f["in_index"] else "no delayed-mode profiles"
                    print(f"  {f['wmo']:>10} | DAC: {f['dac']:>10} | {cycles_info} | {f['name']} [{status}]")
                return
            
            # Determine which floats to download
            if args.float:
                wanted = [w.strip() for w in args.float.split(",")]
                selected = [f for f in float_list if f["wmo"] in wanted]
                missing = [w for w in wanted if w not in {f["wmo"] for f in selected}]
                if missing:
                    print(f"Error: Float(s) {missing} not in target list")
                    sys.exit(1)
            elif args.all:
                selected = float_list
            else:
                selected = interactive_select(float_list)
            
            print(f"\nSelected {len(selected)} float(s)")
            for f in selected:
                if f["in_index"]:
                    print(f"  - {f['wmo']} (DAC: {f['dac']}, {len(f['cycles'])} cycles): {f['name']}")
                else:
                    print(f"  - {f['wmo']} (DAC: {f['dac']}): {f['name']} [NOT IN INDEX - will skip]")
            
# Confirm
            if not args.all and not args.float:
                confirm = input("\nProceed with download? [y/N]: ").strip().lower()
                if confirm != 'y':
                    print("Cancelled")
                    return
            
            await run_download(args.output, selected)
    
    asyncio.run(fetch_and_run())


if __name__ == "__main__":
    main()